<?php
// $Id: site_help.module,v 1.2.4.1 2010/03/01 21:12:39 fgm Exp $
/**
 * @file
 *
 * Provide example help for the advanced help module.
 */

/**
 * Implementation of hook_menu().
 */
function site_help_menu() {
  // View help topic index.
  $items['admin/site_help'] = array(
    'title' => 'Beth Chaim Web Site Help',
    'page callback' => 'site_help_index_page',
    'access arguments' => array('view advanced help index'),
    'weight' => 9,
  );
  return $items;
}

function site_help_index_page() {
  $output = theme('advanced_help_topic', array(
    'module' => 'site_help',
    'topic' => 'about-php',
  ));
  $output .= '&nbsp;' . t('Click the help icon to view some example help about the PHP programming language (from wikipedia.org). Be sure to run cron to update the index if you want to try out the search features.');
  return $output;
}
